export interface Garment {
  id: string;
  name: string;
  type: 'top' | 'bottom' | 'full' | 'outerwear' | 'shoes' | 'accessory';
  category: string; // Casual, Streetwear, Luxury, Business, Traditional, Y2K, etc.
  subcategory: string;
  gender: 'man' | 'woman' | 'boy' | 'girl' | 'unisex';
  colors: string[]; // Hex codes or color names
  price: number;
  rating: number;
  styleTags: string[];
  description: string;
  // Vector render coordinates mapping relative to pose keypoints
  renderConfig: {
    baseColor: string;
    secondaryColor?: string;
    texture?: 'plain' | 'denim' | 'stripes' | 'plaid' | 'leather' | 'knitted' | 'gold' | 'silver' | 'silk' | 'brocade' | 'artistic' | 'sequins' | 'velvet';
    opacity?: number;
    logoText?: string;
    patternScale?: number;
  };
}

export interface Outfit {
  id: string;
  name: string;
  gender: 'man' | 'woman' | 'boy' | 'girl';
  category: string;
  styleTags: string[];
  items: Garment[];
  description: string;
  totalPrice: number;
}

// Base Garment templates that can be combined and customized
export const BASE_GARMENTS: Garment[] = [
  // --- MEN'S TOPS ---
  {
    id: 'm_top_oversized_black',
    name: 'Oversized Heavyweight Tee',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'T-Shirts',
    gender: 'man',
    colors: ['#0A0A0A', '#FFFFFF', '#4A4A4A', '#2D3A2F'],
    price: 49,
    rating: 4.8,
    styleTags: ['Oversized', 'Heavyweight', 'Box Fit', 'Minimalist'],
    description: 'A boxy, heavyweight cotton tee designed for supreme comfort and streetwear style.',
    renderConfig: { baseColor: '#0A0A0A', texture: 'plain', logoText: 'ESSENTIAL' }
  },
  {
    id: 'm_top_oxford_blue',
    name: 'Oxford Slim Fit Shirt',
    type: 'top',
    category: 'Business',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#D6E4F0', '#FFFFFF', '#1F3C88'],
    price: 79,
    rating: 4.6,
    styleTags: ['Slim Fit', 'Classic', 'Office', 'Elegant'],
    description: 'Tailored premium cotton Oxford shirt suitable for smart-casual and formal styling.',
    renderConfig: { baseColor: '#93B5C6', texture: 'plain' }
  },
  {
    id: 'm_top_cuban_printed',
    name: 'Cuban Collar Printed Shirt',
    type: 'top',
    category: 'Vacation',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#E3B7A3', '#D3E4CD', '#ADC2A9'],
    price: 65,
    rating: 4.7,
    styleTags: ['Relaxed Fit', 'Cuban Collar', 'Linen', 'Summer'],
    description: 'Breathable linen blend shirt with a retro Cuban collar and soft botanical prints.',
    renderConfig: { baseColor: '#E6D5B8', secondaryColor: '#4A5B4E', texture: 'stripes' }
  },
  {
    id: 'm_top_flannel_red',
    name: 'Classic Plaid Flannel',
    type: 'top',
    category: 'Casual',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#B20606', '#000000', '#1C6DD0'],
    price: 55,
    rating: 4.5,
    styleTags: ['Regular Fit', 'Plaid', 'Grunge', 'Winter'],
    description: 'Thick, warm cotton flannel shirt with a timeless red and black plaid pattern.',
    renderConfig: { baseColor: '#8B0000', secondaryColor: '#000000', texture: 'plaid' }
  },
  {
    id: 'm_top_kurta_white',
    name: 'Linen Kurta',
    type: 'top',
    category: 'Traditional',
    subcategory: 'Kurta',
    gender: 'man',
    colors: ['#FFFFFF', '#E6C45E', '#1D4438'],
    price: 70,
    rating: 4.9,
    styleTags: ['Linen', 'Festive', 'Traditional', 'Ethnic'],
    description: 'Premium white linen kurta with detailed embroidery around the collar.',
    renderConfig: { baseColor: '#F5F5F5', secondaryColor: '#D4AF37', texture: 'plain' }
  },
  {
    id: 'm_top_henley_grey',
    name: 'Henley Long-Sleeve Shirt',
    type: 'top',
    category: 'Casual',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#636E72', '#2D3436', '#B2BEC3'],
    price: 45,
    rating: 4.6,
    styleTags: ['Henley', 'Regular Fit', 'Ribbed', 'Waffle Knit'],
    description: 'A cozy cotton Henley shirt featuring a classic 3-button placket and ribbed fabric.',
    renderConfig: { baseColor: '#636E72', texture: 'knitted' }
  },
  {
    id: 'm_top_polo_navy',
    name: 'Classic Polo Collar Tee',
    type: 'top',
    category: 'Business',
    subcategory: 'T-Shirts',
    gender: 'man',
    colors: ['#0F81C4', '#FFFFFF', '#0A0A0A'],
    price: 49,
    rating: 4.7,
    styleTags: ['Polo', 'Pique', 'Sporty', 'Smart Casual'],
    description: 'Timeless pique knit polo shirt featuring contrasting collar tipping and custom branding.',
    renderConfig: { baseColor: '#0F4C81', secondaryColor: '#FFFFFF', texture: 'plain' }
  },
  {
    id: 'm_top_hawaiian_floral',
    name: 'Hawaiian Floral Summer Shirt',
    type: 'top',
    category: 'Vacation',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#FF7675', '#0984E3', '#00B894'],
    price: 52,
    rating: 4.8,
    styleTags: ['Floral', 'Hawaiian', 'Vacation', 'Summer'],
    description: 'Vibrant tropical flower pattern camp shirt designed to keep you cool under the sun.',
    renderConfig: { baseColor: '#D63031', secondaryColor: '#FDCB6E', texture: 'stripes' }
  },
  {
    id: 'm_top_mandarin_white',
    name: 'Mandarin Collar Linen Shirt',
    type: 'top',
    category: 'Luxury',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#FFFFFF', '#DFE6E9', '#2C3E50'],
    price: 75,
    rating: 4.9,
    styleTags: ['Mandarin Collar', 'Linen', 'Luxury', 'Clean Fit'],
    description: 'A sophisticated collarless shirt tailored from breathable linen for an effortless resort feel.',
    renderConfig: { baseColor: '#FAFAFA', texture: 'plain' }
  },

  // --- MEN'S BOTTOMS ---
  {
    id: 'm_bot_cargo_olive',
    name: 'Loose Fit Cargo Pants',
    type: 'bottom',
    category: 'Streetwear',
    subcategory: 'Pants',
    gender: 'man',
    colors: ['#3A5035', '#0E0E0E', '#C0A080'],
    price: 89,
    rating: 4.7,
    styleTags: ['Baggy', 'Cargo', 'Techwear', 'Utility'],
    description: 'Durable cotton-twill cargo pants featuring multi-pocket utility utility straps.',
    renderConfig: { baseColor: '#4F5D2F', texture: 'plain' }
  },
  {
    id: 'm_bot_denim_straight',
    name: 'Classic Straight Leg Jeans',
    type: 'bottom',
    category: 'Casual',
    subcategory: 'Jeans',
    gender: 'man',
    colors: ['#2B4C7E', '#1A1A1A', '#607274'],
    price: 99,
    rating: 4.8,
    styleTags: ['Straight', 'Raw Denim', 'Vintage', 'Everyday'],
    description: 'High-quality Japanese selvedge denim jeans cut in a clean, straight profile.',
    renderConfig: { baseColor: '#2C5E8A', texture: 'denim' }
  },
  {
    id: 'm_bot_chinos_khaki',
    name: 'Slim Fit Stretch Chinos',
    type: 'bottom',
    category: 'Business',
    subcategory: 'Pants',
    gender: 'man',
    colors: ['#C3B091', '#2C3E50', '#7F8C8D'],
    price: 69,
    rating: 4.6,
    styleTags: ['Slim Fit', 'Chinos', 'Smart Casual', 'Office'],
    description: 'Versatile stretch cotton chinos with a modern tapered leg and clean finish.',
    renderConfig: { baseColor: '#D2B48C', texture: 'plain' }
  },

  // --- MEN'S OUTERWEAR ---
  {
    id: 'm_out_leather_biker',
    name: 'Classic Leather Biker Jacket',
    type: 'outerwear',
    category: 'Luxury',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#111111', '#4A3B32'],
    price: 299,
    rating: 4.9,
    styleTags: ['Leather', 'Biker', 'Vintage', 'Premium'],
    description: 'Heavyweight full-grain leather jacket with metallic zippers and asymmetric lapels.',
    renderConfig: { baseColor: '#1A1A1A', texture: 'leather' }
  },
  {
    id: 'm_out_blazer_navy',
    name: 'Tailored Wool Blazer',
    type: 'outerwear',
    category: 'Luxury',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#0B1B3D', '#2B2B2B'],
    price: 189,
    rating: 4.8,
    styleTags: ['Tailored', 'Blazer', 'Formal', 'Office'],
    description: 'Sartorial single-breasted blazer in structured wool-blend fabric with gold buttons.',
    renderConfig: { baseColor: '#10254C', secondaryColor: '#D4AF37', texture: 'plain' }
  },

  // --- WOMEN'S TOPS ---
  {
    id: 'w_top_crop_white',
    name: 'Ribbed Knit Crop Top',
    type: 'top',
    category: 'Casual',
    subcategory: 'Crop Tops',
    gender: 'woman',
    colors: ['#FFFFFF', '#0A0A0A', '#E0A899', '#B5C99A'],
    price: 29,
    rating: 4.7,
    styleTags: ['Crop', 'Ribbed', 'Knit', 'Y2K'],
    description: 'Sleek, body-hugging ribbed knit halter top perfect for layering or warm days.',
    renderConfig: { baseColor: '#FAFAFA', texture: 'knitted' }
  },
  {
    id: 'w_top_oversized_shirt',
    name: 'Boyfriend Linen Shirt',
    type: 'top',
    category: 'Vacation',
    subcategory: 'Oversized Shirts',
    gender: 'woman',
    colors: ['#FFFFFF', '#D9D7F1', '#FFD3B6'],
    price: 59,
    rating: 4.8,
    styleTags: ['Oversized', 'Linen', 'Minimalist', 'Summer'],
    description: 'Lightweight linen shirt featuring an ultra-relaxed, airy silhouette.',
    renderConfig: { baseColor: '#EBEBEB', texture: 'plain' }
  },
  {
    id: 'w_top_kurti_floral',
    name: 'Chanderi Silk Kurti',
    type: 'top',
    category: 'Traditional',
    subcategory: 'Kurtis',
    gender: 'woman',
    colors: ['#E84545', '#903749', '#FFD369'],
    price: 69,
    rating: 4.9,
    styleTags: ['Floral', 'Silk', 'Traditional', 'Festive'],
    description: 'Elegant silk kurti with intricate floral motifs and gold zari border details.',
    renderConfig: { baseColor: '#D63031', secondaryColor: '#FFD700', texture: 'plain' }
  },
  {
    id: 'w_top_silk_satin',
    name: 'Silk Satin Wrap Blouse',
    type: 'top',
    category: 'Luxury',
    subcategory: 'Blouses',
    gender: 'woman',
    colors: ['#E84393', '#FFFFFF', '#2D3436'],
    price: 68,
    rating: 4.8,
    styleTags: ['Silk', 'Satin', 'Luxury', 'Elegant'],
    description: 'Luxurious silk satin blouse featuring a wrap bodice and elegant cuffed bishop sleeves.',
    renderConfig: { baseColor: '#D63031', texture: 'silk' }
  },
  {
    id: 'w_top_tiedye_pink',
    name: 'Tie-Dye Summer Tee',
    type: 'top',
    category: 'Casual',
    subcategory: 'T-Shirts',
    gender: 'woman',
    colors: ['#FF7675', '#74B9FF', '#FFEAA7'],
    price: 32,
    rating: 4.5,
    styleTags: ['Tie-Dye', 'Relaxed Fit', 'Cotton', 'Summer'],
    description: 'Fun, pastel tie-dye crop tee made of ultra-soft organic combed cotton.',
    renderConfig: { baseColor: '#E84393', secondaryColor: '#FFEAA7', texture: 'stripes' }
  },
  {
    id: 'w_top_offshoulder_black',
    name: 'Off-Shoulder Ribbed Top',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Tops',
    gender: 'woman',
    colors: ['#0A0A0A', '#FFFFFF', '#6C5CE7'],
    price: 38,
    rating: 4.6,
    styleTags: ['Off-Shoulder', 'Ribbed', 'Chic', 'Night Out'],
    description: 'Fashionable fold-over off-the-shoulder ribbed top that defines collarbones.',
    renderConfig: { baseColor: '#0A0A0A', texture: 'knitted' }
  },

  // --- WOMEN'S BOTTOMS ---
  {
    id: 'w_bot_wide_denim',
    name: 'High Waist Wide Leg Jeans',
    type: 'bottom',
    category: 'Streetwear',
    subcategory: 'Jeans',
    colors: ['#4E89AE', '#142850', '#2E3944'],
    gender: 'woman',
    price: 89,
    rating: 4.8,
    styleTags: ['High Waist', 'Wide Leg', 'Retro', 'Comfort'],
    description: 'Vintage-inspired high-waisted denim jeans featuring a flattering wide-leg cut.',
    renderConfig: { baseColor: '#3B7A57', texture: 'denim' }
  },
  {
    id: 'w_bot_cargo_black',
    name: 'Tech Utility Cargo Pants',
    type: 'bottom',
    category: 'Streetwear',
    subcategory: 'Cargo Pants',
    gender: 'woman',
    colors: ['#0A0A0A', '#394A51', '#7286D3'],
    price: 79,
    rating: 4.6,
    styleTags: ['Cargo', 'Techwear', 'Streetwear', 'Tapered'],
    description: 'Urban utility pants with oversized pockets, elastic cuffs, and high waist rise.',
    renderConfig: { baseColor: '#121212', texture: 'plain' }
  },
  {
    id: 'w_bot_skirt_satin',
    name: 'Satin Midi Skirt',
    type: 'bottom',
    category: 'Luxury',
    subcategory: 'Maxi Skirts',
    gender: 'woman',
    colors: ['#D7C49E', '#343148', '#8B5A2B'],
    price: 75,
    rating: 4.7,
    styleTags: ['Midi', 'Satin', 'Elegant', 'Chic'],
    description: 'High-waisted bias cut satin skirt that drapes beautifully over body contours.',
    renderConfig: { baseColor: '#C5A880', texture: 'plain' }
  },

  // --- WOMEN'S FULL BODY ---
  {
    id: 'w_full_bodycon_black',
    name: 'Ribbed Knit Bodycon Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Bodycon Dresses',
    gender: 'woman',
    colors: ['#0F0F0F', '#7D1C1C', '#1D3557'],
    price: 110,
    rating: 4.8,
    styleTags: ['Bodycon', 'Knit', 'Mini', 'Cocktail'],
    description: 'A stunning bodycon mini dress designed to define and hug your silhouette.',
    renderConfig: { baseColor: '#111111', texture: 'knitted' }
  },
  {
    id: 'w_full_saree_silk',
    name: 'Banarasi Silk Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#990000', '#004d4d', '#4a154b'],
    price: 240,
    rating: 5.0,
    styleTags: ['Silk', 'Traditional', 'Banarasi', 'Wedding'],
    description: 'Luxury gold-woven Banarasi silk saree with ornate floral border borders.',
    renderConfig: { baseColor: '#800020', secondaryColor: '#FFD700', texture: 'brocade' }
  },
  {
    id: 'w_full_lehenga_choli',
    name: 'Floral Embroidered Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#FF66B2', '#40E0D0', '#E6E6FA'],
    price: 320,
    rating: 4.9,
    styleTags: ['Traditional', 'Lehenga', 'Embroidery', 'Festive'],
    description: 'Stunning three-piece lehenga choli set with dense mirror and floral thread work.',
    renderConfig: { baseColor: '#FF1493', secondaryColor: '#FFE4E1', texture: 'brocade' }
  },

  // --- ACCESSORIES ---
  {
    id: 'acc_sunglasses_aviator',
    name: 'Hexagonal Gold Aviators',
    type: 'accessory',
    category: 'Luxury',
    subcategory: 'Sunglasses',
    gender: 'unisex',
    colors: ['#D4AF37'],
    price: 150,
    rating: 4.9,
    styleTags: ['Gold', 'Hexagonal', 'Retro', 'Premium'],
    description: 'Premium lightweight metal aviators featuring dark green tinted UV lenses.',
    renderConfig: { baseColor: '#FFD700', secondaryColor: '#006400', texture: 'gold' }
  },
  {
    id: 'acc_watch_silver',
    name: 'Chronograph Steel Watch',
    type: 'accessory',
    category: 'Luxury',
    subcategory: 'Watches',
    gender: 'unisex',
    colors: ['#C0C0C0'],
    price: 250,
    rating: 4.8,
    styleTags: ['Steel', 'Classic', 'Waterproof', 'Office'],
    description: 'A timeless automatic watch crafted in brushed surgical-grade stainless steel.',
    renderConfig: { baseColor: '#C0C0C0', texture: 'silver' }
  },
  {
    id: 'acc_bag_leather',
    name: 'Structured Leather Crossbody',
    type: 'accessory',
    category: 'Luxury',
    subcategory: 'Handbags',
    gender: 'woman',
    colors: ['#5C4033', '#000000'],
    price: 195,
    rating: 4.7,
    styleTags: ['Leather', 'Saddle Bag', 'Elegant', 'Everyday'],
    description: 'Crafted from Italian pebbled leather with a gold buckle and adjustable strap.',
    renderConfig: { baseColor: '#8B4513', secondaryColor: '#FFD700', texture: 'leather' }
  },

  // --- SHOES ---
  {
    id: 'shoes_sneakers_retro',
    name: 'Retro Leather Court Sneakers',
    type: 'shoes',
    category: 'Streetwear',
    subcategory: 'Sneakers',
    gender: 'unisex',
    colors: ['#FFFFFF', '#1A1A1A'],
    price: 110,
    rating: 4.7,
    styleTags: ['Leather', 'Minimalist', 'Retro', 'Comfort'],
    description: 'Clean low-top sneakers in premium calfskin leather with a vintage gum sole.',
    renderConfig: { baseColor: '#FFFFFF', secondaryColor: '#D2B48C', texture: 'plain' }
  },
  {
    id: 'shoes_boots_chelsea',
    name: 'Suede Chelsea Boots',
    type: 'shoes',
    category: 'Luxury',
    subcategory: 'Boots',
    gender: 'unisex',
    colors: ['#8B7355', '#2B2B2B'],
    price: 180,
    rating: 4.8,
    styleTags: ['Suede', 'Chelsea', 'Slip-on', 'Classic'],
    description: 'Premium Italian suede Chelsea boots with flexible side panels and crepe soles.',
    renderConfig: { baseColor: '#A0522D', texture: 'plain' }
  },
  {
    id: 'shoes_w_stiletto_heels',
    name: 'Stiletto Patent Heels',
    type: 'shoes',
    category: 'Luxury',
    subcategory: 'Heels',
    gender: 'woman',
    colors: ['#0A0A0A', '#B22222', '#FDFBF7'],
    price: 165,
    rating: 4.9,
    styleTags: ['Patent', 'Luxury', 'Heels', 'Formal'],
    description: 'Elegant high-gloss patent leather stiletto pumps for formal and luxury wear.',
    renderConfig: { baseColor: '#0A0A0A', texture: 'plain' }
  },
  {
    id: 'shoes_w_strappy_sandals',
    name: 'Strappy Leather Sandals',
    type: 'shoes',
    category: 'Vacation',
    subcategory: 'Sandals',
    gender: 'woman',
    colors: ['#D2B48C', '#FFFFFF'],
    price: 95,
    rating: 4.7,
    styleTags: ['Strappy', 'Leather', 'Summer', 'Vacation'],
    description: 'Minimalist strappy leather sandals perfect for resort and vacation walks.',
    renderConfig: { baseColor: '#D2B48C', texture: 'plain' }
  },
  {
    id: 'shoes_w_ballet_flats',
    name: 'Classic Ballet Flats',
    type: 'shoes',
    category: 'Casual',
    subcategory: 'Flats',
    gender: 'woman',
    colors: ['#FFB6C1', '#0A0A0A', '#E6D5B8'],
    price: 85,
    rating: 4.6,
    styleTags: ['Casual', 'Flats', 'Leather', 'Classic'],
    description: 'Chic and comfortable leather ballet flats with a subtle bow detail.',
    renderConfig: { baseColor: '#FFB6C1', texture: 'plain' }
  },
  {
    id: 'shoes_m_leather_loafers',
    name: 'Classic Leather Loafers',
    type: 'shoes',
    category: 'Business',
    subcategory: 'Loafers',
    gender: 'man',
    colors: ['#4A2E1B', '#0A0A0A'],
    price: 170,
    rating: 4.8,
    styleTags: ['Leather', 'Business', 'Classic', 'Sartorial'],
    description: 'Timeless hand-crafted leather loafers ideal for office and smart-casual fits.',
    renderConfig: { baseColor: '#4A2E1B', texture: 'plain' }
  },
  {
    id: 'shoes_m_derby_shoes',
    name: 'Oxford Derby Shoes',
    type: 'shoes',
    category: 'Formal',
    subcategory: 'Derby',
    gender: 'man',
    colors: ['#0A0A0A', '#5C4033'],
    price: 195,
    rating: 4.9,
    styleTags: ['Leather', 'Formal', 'Dress Shoes', 'Suit'],
    description: 'Polished calfskin leather Derby dress shoes for suits and black-tie events.',
    renderConfig: { baseColor: '#0A0A0A', texture: 'plain' }
  },
  {
    id: 'acc_w_dupatta',
    name: 'Gold Embroidered Dupatta',
    type: 'accessory',
    category: 'Traditional',
    subcategory: 'Scarves',
    gender: 'woman',
    colors: ['#D4AF37', '#B22222', '#0F1E36'],
    price: 60,
    rating: 4.9,
    styleTags: ['Traditional', 'Accessory', 'Gold', 'Silk'],
    description: 'A heavy organza dupatta bordered with intricate gold zari embroidery.',
    renderConfig: { baseColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'acc_w_clutch_bag',
    name: 'Satin Envelope Clutch',
    type: 'accessory',
    category: 'Luxury',
    subcategory: 'Bags',
    gender: 'woman',
    colors: ['#0A0A0A', '#FAFAFA', '#D4AF37'],
    price: 120,
    rating: 4.8,
    styleTags: ['Luxury', 'Satin', 'Evening', 'Classic'],
    description: 'A sleek evening envelope clutch in glossy satin with gold metallic hardware.',
    renderConfig: { baseColor: '#0A0A0A', texture: 'plain' }
  },
  {
    id: 'acc_w_leather_handbag',
    name: 'Classic Leather Tote Bag',
    type: 'accessory',
    category: 'Business',
    subcategory: 'Bags',
    gender: 'woman',
    colors: ['#D2B48C', '#0A0A0A', '#ADC2A9'],
    price: 210,
    rating: 4.7,
    styleTags: ['Leather', 'Tote', 'Business', 'Everyday'],
    description: 'A spacious premium pebbled leather tote bag with sturdy handles.',
    renderConfig: { baseColor: '#D2B48C', texture: 'leather' }
  },
  {
    id: 'm_top_artistic_paint',
    name: 'Abstract Paint Splatter Tee',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'T-Shirts',
    gender: 'man',
    colors: ['#0A0A0A', '#FFFFFF'],
    price: 55,
    rating: 4.9,
    styleTags: ['Artistic', 'Paint Splatter', 'Streetwear', 'Oversized', 'Colorful'],
    description: 'A premium heavy-weight cotton tee featuring abstract hand-painted brushstroke splash patterns.',
    renderConfig: { baseColor: '#0A0A0A', secondaryColor: '#EC4899', texture: 'artistic' }
  },
  {
    id: 'w_full_artistic_dress',
    name: 'Artistic Paint Splash Dress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFFFFF', '#EC4899', '#3B82F6'],
    price: 135,
    rating: 4.9,
    styleTags: ['Artistic', 'Boho', 'Maxi', 'Paint Splatter', 'Colorful'],
    description: 'A beautiful flowing maxi dress printed with wavy abstract designer brushstrokes.',
    renderConfig: { baseColor: '#FFFFFF', secondaryColor: '#EC4899', texture: 'artistic' }
  },
  {
    id: 'w_full_sequin_gold',
    name: 'Glitzy Gold Sequin Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#D4AF37', '#FFDF00', '#B8860B'],
    price: 290,
    rating: 5.0,
    styleTags: ['Sequin', 'Maxi', 'Runway', 'Glow', 'Glitter', 'Luxury'],
    description: 'An absolute show-stopper maxi gown drenched in hundreds of hand-stitched gold sequins that shimmer under lights.',
    renderConfig: { baseColor: '#D4AF37', secondaryColor: '#FFFFFF', texture: 'sequins' }
  },
  {
    id: 'w_full_sequin_silver',
    name: 'Starlight Silver Sequin Gown',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#E6E6FA', '#FFFFFF', '#A9A9A9'],
    price: 320,
    rating: 4.9,
    styleTags: ['Sequin', 'Maxi', 'Runway', 'Glow', 'Glitter', 'Luxury', 'V-Neck'],
    description: 'A breathtaking runway sequin dress that glints with starlight silver shimmer. Features an elegant V-neck cut.',
    renderConfig: { baseColor: '#E6E6FA', secondaryColor: '#FFFFFF', texture: 'sequins' }
  },
  {
    id: 'w_full_royal_brocade',
    name: 'Royal Emerald Zari Brocade Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#1B4D3E', '#D4AF37', '#0F2C20'],
    price: 420,
    rating: 5.0,
    styleTags: ['Brocade', 'Traditional', 'Lehenga', 'Luxury', 'Embroidery'],
    description: 'A magnificent lehenga choli made of heavy silk brocade with detailed hand-woven gold zari embroidery borders.',
    renderConfig: { baseColor: '#1B4D3E', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_full_ruby_silk',
    name: 'Ruby Red Silk Wrap Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#B31B1B', '#D4AF37', '#7A0A0A'],
    price: 195,
    rating: 4.8,
    styleTags: ['Silk', 'Elegant', 'Maxi', 'Luxury', 'V-Neck'],
    description: 'A luxurious ruby red silk wrap gown with a dynamic overhead shimmer sheen and a plunging V-neck collar.',
    renderConfig: { baseColor: '#B31B1B', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_full_galaxy_glow',
    name: 'Celestial Galaxy Glow Gown',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#3B0A4E', '#00F2FE', '#EC4899'],
    price: 380,
    rating: 4.9,
    styleTags: ['Glow', 'Glitter', 'Maxi', 'Runway', 'Artistic'],
    description: 'A futuristic runway gown reflecting celestial neon space dust paint strokes, glowing with a bright cyan outer rim.',
    renderConfig: { baseColor: '#3B0A4E', secondaryColor: '#00F2FE', texture: 'artistic' }
  },
  {
    id: 'w_full_boho_paisley',
    name: 'Vintage Boho Paisley Tiered Dress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#D2691E', '#D4AF37', '#8B4513'],
    price: 165,
    rating: 4.7,
    styleTags: ['Boho', 'Paisley', 'Casual', 'Maxi', 'Orange'],
    description: 'A beautiful tiered vintage boho dress printed with gold-embroidered paisley swirls.',
    renderConfig: { baseColor: '#D2691E', secondaryColor: '#D4AF37', texture: 'artistic' }
  },
  {
    id: 'w_full_midnight_glimmer',
    name: 'Midnight Indigo Glimmer Gown',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#191970', '#00BFFF', '#0B0B3B'],
    price: 340,
    rating: 4.9,
    styleTags: ['Sequin', 'Maxi', 'Runway', 'Glow', 'Luxury'],
    description: 'An exquisite evening gown reflecting deep indigo sequins that shimmer like a starry midnight sky.',
    renderConfig: { baseColor: '#191970', secondaryColor: '#00BFFF', texture: 'sequins' }
  },
  {
    id: 'w_full_velvet_tuxedo',
    name: 'Royal Crimson Velvet Tuxedo Dress',
    type: 'full',
    category: 'Formal',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#800020', '#D4AF37', '#3A000A'],
    price: 360,
    rating: 4.9,
    styleTags: ['Formal', 'Runway', 'Brocade', 'Velvet', 'Luxury'],
    description: 'A luxurious deep crimson velvet blazer-style dress featuring shiny gold buttons and gold brocade trim.',
    renderConfig: { baseColor: '#800020', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'w_full_vintage_summer',
    name: 'Sunkissed Vintage Floral Sundress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFD700', '#FF6B6B', '#FFA500'],
    price: 190,
    rating: 4.8,
    styleTags: ['Boho', 'Floral', 'Casual', 'Maxi', 'Artistic'],
    description: 'A bright yellow vintage floral sundress with coral orange abstract brush strokes.',
    renderConfig: { baseColor: '#FFD700', secondaryColor: '#FF6B6B', texture: 'artistic' }
  },
  {
    id: 'w_full_emerald_sash',
    name: 'Royal Emerald Satin Ribbon Gown',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#004B23', '#D4AF37', '#00240F'],
    price: 280,
    rating: 4.9,
    styleTags: ['Maxi', 'Luxury', 'Party', 'Satin', 'Glow'],
    description: 'An exquisite emerald green satin gown featuring a waist sash ribbon and a polished golden belt buckle clasp.',
    renderConfig: { baseColor: '#004B23', secondaryColor: '#D4AF37', texture: 'plain' }
  },
  {
    id: 'w_full_rosegold_glitz',
    name: 'Rose Gold Glitz Evening Gown',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#B76E79', '#F0E68C', '#8A4F58'],
    price: 310,
    rating: 4.9,
    styleTags: ['Sequin', 'Maxi', 'Elegant', 'Glow', 'Luxury'],
    description: 'A glamorous rose gold sequined evening gown that sparkles with champagne gold highlights.',
    renderConfig: { baseColor: '#B76E79', secondaryColor: '#F0E68C', texture: 'sequins' }
  },
  {
    id: 'w_full_lavender_haze',
    name: 'Lavender Haze Silk Wrap Gown',
    type: 'full',
    category: 'Casual',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#E6E6FA', '#C0C0C0', '#B0B0D0'],
    price: 175,
    rating: 4.8,
    styleTags: ['Silk', 'Elegant', 'Maxi', 'V-Neck', 'Lavender'],
    description: 'A dreamy lavender silk wrap dress with subtle silver thread highlights and a flared sleeve.',
    renderConfig: { baseColor: '#E6E6FA', secondaryColor: '#C0C0C0', texture: 'silk' }
  },
  {
    id: 'w_full_scarlet_brocade',
    name: 'Scarlet Brocade Festive Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#FF2400', '#E5A93B', '#800A00'],
    price: 450,
    rating: 4.9,
    styleTags: ['Brocade', 'Traditional', 'Lehenga', 'Luxury', 'Embroidery'],
    description: 'A festive scarlet red lehenga featuring rich brocade fabric and detailed gold embroidery panels.',
    renderConfig: { baseColor: '#FF2400', secondaryColor: '#E5A93B', texture: 'brocade' }
  },
  {
    id: 'w_full_midnight_saree',
    name: 'Midnight Georgette Zari Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#120A2A', '#D4AF37', '#06030F'],
    price: 380,
    rating: 5.0,
    styleTags: ['Traditional', 'Saree', 'Silk', 'Luxury', 'Gold'],
    description: 'A royal midnight georgette saree featuring intricate hand-woven gold zari borders.',
    renderConfig: { baseColor: '#120A2A', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_full_cyber_punk',
    name: 'Cyberpunk Holographic Neon Dress',
    type: 'full',
    category: 'Streetwear',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#8A2BE2', '#00FFFF', '#4B0082'],
    price: 220,
    rating: 4.8,
    styleTags: ['Streetwear', 'Hologram', 'Glow', 'Neon', 'Artistic'],
    description: 'A streetwear holographic jersey dress with neon cyan accents that glow under dark light.',
    renderConfig: { baseColor: '#8A2BE2', secondaryColor: '#00FFFF', texture: 'artistic' }
  },
  {
    id: 'w_full_marigold_boho',
    name: 'Marigold Boho Tassel Sundress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FF8C00', '#FFFDD0', '#D2691E'],
    price: 155,
    rating: 4.7,
    styleTags: ['Boho', 'Vacation', 'Maxi', 'Casual', 'Yellow'],
    description: 'A breezy tiered boho sundress in marigold orange printed with cream mandala motifs.',
    renderConfig: { baseColor: '#FF8C00', secondaryColor: '#FFFDD0', texture: 'artistic' }
  },
  {
    id: 'w_full_emerald_gown',
    name: 'Emerald Velvet Evening Gown',
    type: 'full',
    category: 'Formal',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0F2E23', '#D4AF37'],
    price: 310,
    rating: 4.9,
    styleTags: ['Formal', 'Gown', 'Velvet', 'Luxury', 'Long Sleeve'],
    description: 'A luxurious deep emerald green velvet gown with a formal flared silhouette.',
    renderConfig: { baseColor: '#0F2E23', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'w_full_gold_sequin',
    name: 'Gold Dust Sequin Cocktail Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#E6C45E', '#FFFDD0'],
    price: 260,
    rating: 4.8,
    styleTags: ['Party', 'Cocktail', 'Sequin', 'Glow', 'Mini'],
    description: 'A stunning champagne gold mini cocktail dress woven with light-catching sequins.',
    renderConfig: { baseColor: '#E6C45E', secondaryColor: '#FFFDD0', texture: 'sequins' }
  },
  {
    id: 'w_full_crimson_lace',
    name: 'Victorian Crimson Lace Dress',
    type: 'full',
    category: 'Business',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#800020', '#FFD700'],
    price: 290,
    rating: 4.7,
    styleTags: ['Classic', 'Elegant', 'Office', 'Brocade'],
    description: 'A structured lace-panelled A-line dress in rich crimson red with gold trims.',
    renderConfig: { baseColor: '#800020', secondaryColor: '#FFD700', texture: 'brocade' }
  },
  {
    id: 'w_full_sapphire_wrap',
    name: 'Sapphire Shimmer Silk Wrap',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0F1E36', '#C0C0C0'],
    price: 340,
    rating: 5.0,
    styleTags: ['Luxury', 'Silk', 'Classic', 'Long Sleeve'],
    description: 'A royal sapphire blue wrap dress in liquid-silk fabric with parallel silver cuff trims.',
    renderConfig: { baseColor: '#0F1E36', secondaryColor: '#C0C0C0', texture: 'silk' }
  },
  {
    id: 'w_full_meadow_maxi',
    name: 'Summer Meadow Floral Maxi',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFFDD0', '#2ECC71'],
    price: 175,
    rating: 4.6,
    styleTags: ['Vacation', 'Maxi', 'Floral', 'Boho', 'Artistic'],
    description: 'A flowing cream-colored maxi dress printed with wild meadow flowers.',
    renderConfig: { baseColor: '#FFFDD0', secondaryColor: '#2ECC71', texture: 'artistic' }
  },
  {
    id: 'w_full_ivory_lehenga',
    name: 'Ivory Brocade Bridal Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#FDFBF7', '#D4AF37'],
    price: 480,
    rating: 5.0,
    styleTags: ['Traditional', 'Lehenga', 'Brocade', 'Luxury', 'Gold'],
    description: 'An opulent ivory traditional lehenga featuring gold zari woven motifs.',
    renderConfig: { baseColor: '#FDFBF7', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_full_ruby_saree',
    name: 'Ruby Silk Banarasi Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#B22222', '#D4AF37'],
    price: 420,
    rating: 4.9,
    styleTags: ['Traditional', 'Saree', 'Silk', 'Luxury', 'Gold'],
    description: 'A vibrant ruby red Banarasi silk saree with heavy gold zari borders.',
    renderConfig: { baseColor: '#B22222', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_full_amethyst_midi',
    name: 'Amethyst Pleated Midi Dress',
    type: 'full',
    category: 'Casual',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#6C5B7B', '#FFFDD0'],
    price: 195,
    rating: 4.7,
    styleTags: ['Casual', 'Elegant', 'Plaid', 'Classic'],
    description: 'An elegant pleated midi dress in soft amethyst purple checkered with cream lines.',
    renderConfig: { baseColor: '#6C5B7B', secondaryColor: '#FFFDD0', texture: 'plaid' }
  },
  {
    id: 'k_girl_full_blossom',
    name: 'Cherry Blossom Silk Frock',
    type: 'full',
    category: 'Casual',
    subcategory: 'Dresses',
    gender: 'girl',
    colors: ['#FFB6C1', '#FFFFFF'],
    price: 85,
    rating: 4.8,
    styleTags: ['Casual', 'Cute', 'Floral', 'Artistic'],
    description: 'A lovely pink cotton party frock printed with cherry blossoms.',
    renderConfig: { baseColor: '#FFB6C1', secondaryColor: '#FFFFFF', texture: 'artistic' }
  },
  {
    id: 'k_boy_full_sherwani',
    name: 'Navy Velvet Prince Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'boy',
    colors: ['#0F172A', '#D4AF37'],
    price: 110,
    rating: 4.9,
    styleTags: ['Traditional', 'Festive', 'Brocade', 'Gold'],
    description: 'A micro royal navy velvet sherwani with detailed gold embroidery borders.',
    renderConfig: { baseColor: '#0F172A', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'w_full_obsidian_gown',
    name: 'Midnight Obsidian Gothic Gown',
    type: 'full',
    category: 'Formal',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0A0A0A', '#FFFFFF'],
    price: 330,
    rating: 4.9,
    styleTags: ['Formal', 'Gown', 'Classic', 'Luxury', 'Black'],
    description: 'A dramatic midnight obsidian black satin gown with structured shoulders and flared skirt.',
    renderConfig: { baseColor: '#0A0A0A', secondaryColor: '#FFFFFF', texture: 'silk' }
  },
  {
    id: 'w_full_quartz_dress',
    name: 'Rose Quartz Organza Dress',
    type: 'full',
    category: 'Casual',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFD1DC', '#FFFFFF'],
    price: 215,
    rating: 4.6,
    styleTags: ['Casual', 'Elegant', 'Silk', 'Pink'],
    description: 'A pastel rose quartz pink organza dress featuring subtle floral detailing.',
    renderConfig: { baseColor: '#FFD1DC', secondaryColor: '#FFFFFF', texture: 'artistic' }
  },
  {
    id: 'w_full_scarlet_cocktail',
    name: 'Scarlet Silk Cocktail Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#D63031', '#D4AF37'],
    price: 245,
    rating: 4.8,
    styleTags: ['Party', 'Cocktail', 'Silk', 'Mini'],
    description: 'A luxurious scarlet red silk cocktail dress with gold embroidery trims.',
    renderConfig: { baseColor: '#D63031', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_full_sunset_maxi',
    name: 'Sunset Ombre Chiffon Maxi',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FF7675', '#FDCB6E'],
    price: 190,
    rating: 4.7,
    styleTags: ['Vacation', 'Maxi', 'Artistic', 'Summer'],
    description: 'A lightweight chiffon maxi dress with a gorgeous orange-to-pink sunset ombre dye.',
    renderConfig: { baseColor: '#FF7675', secondaryColor: '#FDCB6E', texture: 'artistic' }
  },
  {
    id: 'w_full_navy_lehenga',
    name: 'Midnight Velvet Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#0F1E36', '#C0C0C0'],
    price: 460,
    rating: 4.9,
    styleTags: ['Traditional', 'Lehenga', 'Velvet', 'Luxury', 'Silver'],
    description: 'An elegant midnight navy blue velvet lehenga with silver zardozi embroidery borders.',
    renderConfig: { baseColor: '#0F1E36', secondaryColor: '#C0C0C0', texture: 'velvet' }
  },
  {
    id: 'w_full_sage_saree',
    name: 'Sage Green Silk Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#ADC2A9', '#D4AF37'],
    price: 395,
    rating: 4.8,
    styleTags: ['Traditional', 'Saree', 'Silk', 'Luxury', 'Gold'],
    description: 'A soothing sage green silk saree with detailed hand-woven gold borders.',
    renderConfig: { baseColor: '#ADC2A9', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_full_champagne_wrap',
    name: 'Champagne Satin Wrap Dress',
    type: 'full',
    category: 'Formal',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#E6D5B8', '#4A4A4A'],
    price: 285,
    rating: 4.8,
    styleTags: ['Formal', 'Elegant', 'Silk', 'Classic', 'Long Sleeve'],
    description: 'A sophisticated champagne-colored satin wrap dress with detailed stitching.',
    renderConfig: { baseColor: '#E6D5B8', secondaryColor: '#4A4A4A', texture: 'silk' }
  },
  {
    id: 'w_full_fuchsia_glitter',
    name: 'Cyberpunk Fuchsia Glitter Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FF007F', '#00FFFF'],
    price: 235,
    rating: 4.7,
    styleTags: ['Party', 'Glow', 'Sequin', 'Mini', 'Artistic'],
    description: 'A retro-futuristic fuchsia pink dress covered in sparkling sequins and neon highlights.',
    renderConfig: { baseColor: '#FF007F', secondaryColor: '#00FFFF', texture: 'sequins' }
  },
  {
    id: 'k_girl_full_peppermint',
    name: 'Peppermint Summer Sundress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'girl',
    colors: ['#A8E6CF', '#FFFFFF'],
    price: 75,
    rating: 4.6,
    styleTags: ['Vacation', 'Cute', 'Floral', 'Artistic'],
    description: 'A breezy mint green child sundress printed with white daisy patterns.',
    renderConfig: { baseColor: '#A8E6CF', secondaryColor: '#FFFFFF', texture: 'artistic' }
  },
  {
    id: 'k_boy_full_crimson',
    name: 'Royal Crimson Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'boy',
    colors: ['#800020', '#D4AF37'],
    price: 115,
    rating: 4.9,
    styleTags: ['Traditional', 'Festive', 'Brocade', 'Gold'],
    description: 'A majestic crimson red sherwani with gold zari embroidery trims.',
    renderConfig: { baseColor: '#800020', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_full_lavender_gown',
    name: 'Lavender Mist Organza Gown',
    type: 'full',
    category: 'Formal',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#E6E6FA', '#C0C0C0'],
    price: 320,
    rating: 4.9,
    styleTags: ['Formal', 'Gown', 'Classic', 'Luxury', 'Lavender'],
    description: 'A dreamlike lavender organza gown with a layered flared skirt and silver metallic trims.',
    renderConfig: { baseColor: '#E6E6FA', secondaryColor: '#C0C0C0', texture: 'silk' }
  },
  {
    id: 'w_full_velvet_gold',
    name: 'Midnight Gold Velvet Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0A0A0A', '#D4AF37'],
    price: 275,
    rating: 4.8,
    styleTags: ['Party', 'Cocktail', 'Velvet', 'Luxury', 'Gold'],
    description: 'A plush midnight black velvet mini dress featuring an elegant gold embroidered collar and cuffs.',
    renderConfig: { baseColor: '#0A0A0A', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'w_full_boho_terracotta',
    name: 'Terracotta Boho Maxi Dress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#D27D2D', '#FFFDD0'],
    price: 185,
    rating: 4.7,
    styleTags: ['Vacation', 'Maxi', 'Boho', 'Summer'],
    description: 'A flowy terracotta rust cotton maxi dress printed with hand-blocked clay mandalas.',
    renderConfig: { baseColor: '#D27D2D', secondaryColor: '#FFFDD0', texture: 'artistic' }
  },
  {
    id: 'w_full_emerald_saree',
    name: 'Emerald Green Banarasi Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#004F34', '#D4AF37'],
    price: 450,
    rating: 5.0,
    styleTags: ['Traditional', 'Saree', 'Silk', 'Luxury', 'Gold'],
    description: 'A rich forest emerald Banarasi silk saree woven with traditional gold floral bel motifs.',
    renderConfig: { baseColor: '#004F34', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'm_full_gold_sherwani',
    name: 'Royal Gold Brocade Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#DAA520', '#D4AF37'],
    price: 490,
    rating: 5.0,
    styleTags: ['Traditional', 'Sherwani', 'Brocade', 'Luxury', 'Gold'],
    description: 'A royal gold brocade wedding sherwani with detailed hand-woven zari embroidery collars.',
    renderConfig: { baseColor: '#DAA520', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_full_teal_shimmer',
    name: 'Teal Shimmer Wrap Dress',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#005F73', '#C0C0C0'],
    price: 295,
    rating: 4.8,
    styleTags: ['Luxury', 'Silk', 'Classic', 'Long Sleeve'],
    description: 'An elegant deep teal silk wrap dress that shimmers with a dynamic silver sheen.',
    renderConfig: { baseColor: '#005F73', secondaryColor: '#C0C0C0', texture: 'silk' }
  },
  {
    id: 'w_full_coral_sundress',
    name: 'Coral Sun Satin Sundress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FF6F61', '#FFFFFF'],
    price: 160,
    rating: 4.7,
    styleTags: ['Vacation', 'Maxi', 'Summer', 'Artistic'],
    description: 'A vibrant coral pink satin slip sundress featuring thin spaghetti shoulder straps.',
    renderConfig: { baseColor: '#FF6F61', secondaryColor: '#FFFFFF', texture: 'plain' }
  },
  {
    id: 'k_girl_full_lilac',
    name: 'Lilac Garden Party Frock',
    type: 'full',
    category: 'Casual',
    subcategory: 'Dresses',
    gender: 'girl',
    colors: ['#D8B4F8', '#FFFFFF'],
    price: 80,
    rating: 4.8,
    styleTags: ['Casual', 'Cute', 'Floral', 'Artistic'],
    description: 'A whimsical pastel lilac frock with detailed white floral print motifs.',
    renderConfig: { baseColor: '#D8B4F8', secondaryColor: '#FFFFFF', texture: 'artistic' }
  },
  {
    id: 'k_boy_full_ruby_sherwani',
    name: 'Ruby Brocade Prince Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'boy',
    colors: ['#9B111E', '#D4AF37'],
    price: 125,
    rating: 4.9,
    styleTags: ['Traditional', 'Festive', 'Brocade', 'Gold'],
    description: 'A luxury ruby red kids sherwani styled with micro-gold zari thread trim.',
    renderConfig: { baseColor: '#9B111E', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'm_full_charcoal_suit',
    name: 'Charcoal Tweed Blazer Suit',
    type: 'full',
    category: 'Business',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#36454F', '#FFFFFF'],
    price: 380,
    rating: 4.9,
    styleTags: ['Business', 'Suit', 'Classic', 'Elegant', 'Grey'],
    description: 'A tailored charcoal grey tweed blazer suit paired with matching slacks and a white shirt.',
    renderConfig: { baseColor: '#36454F', secondaryColor: '#FFFFFF', texture: 'plain' }
  },
  {
    id: 'm_top_sapphire_jacket',
    name: 'Sapphire Velvet Dinner Jacket',
    type: 'top',
    category: 'Formal',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#0F2C59', '#0A0A0A'],
    price: 260,
    rating: 4.9,
    styleTags: ['Formal', 'Classic', 'Velvet', 'Luxury', 'Blue'],
    description: 'A luxury sapphire blue velvet shawl collar dinner jacket with satin trim lapels.',
    renderConfig: { baseColor: '#0F2C59', secondaryColor: '#0A0A0A', texture: 'velvet' }
  },
  {
    id: 'm_top_emerald_linen',
    name: 'Emerald Linen Summer Shirt',
    type: 'top',
    category: 'Vacation',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#124E3F', '#FFFDD0'],
    price: 85,
    rating: 4.7,
    styleTags: ['Vacation', 'Summer', 'Linen', 'Green'],
    description: 'A lightweight, breathable emerald green long-sleeve linen shirt perfect for warm weather.',
    renderConfig: { baseColor: '#124E3F', secondaryColor: '#FFFDD0', texture: 'plain' }
  },
  {
    id: 'm_full_crimson_kurta_jacket',
    name: 'Crimson Silk Kurta Jacket',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Kurta',
    gender: 'man',
    colors: ['#8B0000', '#D4AF37'],
    price: 220,
    rating: 4.8,
    styleTags: ['Traditional', 'Festive', 'Silk', 'Red', 'Gold'],
    description: 'A premium raw silk crimson red kurta set layered with a gold embroidered Nehru vest.',
    renderConfig: { baseColor: '#8B0000', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'm_full_navy_bandhgala',
    name: 'Royal Navy Bandhgala Suit',
    type: 'full',
    category: 'Formal',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#1D2A44', '#D4AF37'],
    price: 340,
    rating: 4.9,
    styleTags: ['Formal', 'Classic', 'Traditional', 'Blue', 'Gold'],
    description: 'An elegant royal navy blue bandhgala jodhpuri suit detailed with brass gold buttons.',
    renderConfig: { baseColor: '#1D2A44', secondaryColor: '#D4AF37', texture: 'plain' }
  },
  {
    id: 'm_full_ivory_sherwani',
    name: 'Ivory Zari Silk Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#FFFFF0', '#D4AF37'],
    price: 460,
    rating: 5.0,
    styleTags: ['Traditional', 'Sherwani', 'Luxury', 'Gold', 'Ivory'],
    description: 'A luxurious ivory white raw silk sherwani intricately embroidered with gold zari threads.',
    renderConfig: { baseColor: '#FFFFF0', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'm_top_sandstone_suede',
    name: 'Sandstone Suede Trucker Jacket',
    type: 'top',
    category: 'Casual',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#C2B280', '#C0C0C0'],
    price: 195,
    rating: 4.7,
    styleTags: ['Casual', 'Tweed', 'Autumn', 'Sand'],
    description: 'A premium sandstone brown suede trucker jacket detailed with silver button studs.',
    renderConfig: { baseColor: '#C2B280', secondaryColor: '#C0C0C0', texture: 'denim' }
  },
  {
    id: 'm_top_truffle_cashmere',
    name: 'Truffle Brown Cashmere Sweater',
    type: 'top',
    category: 'Casual',
    subcategory: 'Sweaters',
    gender: 'man',
    colors: ['#3D2314', '#000000'],
    price: 140,
    rating: 4.8,
    styleTags: ['Casual', 'Classic', 'Knit', 'Brown'],
    description: 'A super-soft truffle brown cashmere crewneck sweater woven in a detailed knit pattern.',
    renderConfig: { baseColor: '#3D2314', secondaryColor: '#000000', texture: 'knitted' }
  },
  {
    id: 'm_bottom_pleated_trousers',
    name: 'Off-White Pleated Trousers',
    type: 'bottom',
    category: 'Business',
    subcategory: 'Pants',
    gender: 'man',
    colors: ['#F5F5F0', '#CCCCCC'],
    price: 110,
    rating: 4.6,
    styleTags: ['Business', 'Classic', 'Linen', 'White'],
    description: 'Tailored off-white linen-tweed blend pleated trousers with side adjustment tabs.',
    renderConfig: { baseColor: '#F5F5F0', secondaryColor: '#CCCCCC', texture: 'plain' }
  },
  {
    id: 'm_top_bronze_nehru',
    name: 'Bronze Brocade Nehru Vest',
    type: 'top',
    category: 'Traditional',
    subcategory: 'Vests',
    gender: 'man',
    colors: ['#CD7F32', '#D4AF37'],
    price: 135,
    rating: 4.8,
    styleTags: ['Traditional', 'Festive', 'Brocade', 'Bronze'],
    description: 'A rich bronze brocade Nehru jacket detailed with intricate floral patterns.',
    renderConfig: { baseColor: '#CD7F32', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'm_full_onyx_trench',
    name: 'Onyx Black Trench Coat',
    type: 'full',
    category: 'Formal',
    subcategory: 'Coats',
    gender: 'man',
    colors: ['#050505', '#FFFFFF'],
    price: 290,
    rating: 4.9,
    styleTags: ['Formal', 'Classic', 'Leather', 'Black'],
    description: 'A classic double-breasted onyx black waterproof trench coat with belt strap detailing.',
    renderConfig: { baseColor: '#050505', secondaryColor: '#FFFFFF', texture: 'leather' }
  },
  {
    id: 'm_full_gold_festive_sherwani',
    name: 'Golden Silk Festive Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#D4AF37', '#FFFFF0'],
    price: 480,
    rating: 4.9,
    styleTags: ['Traditional', 'Sherwani', 'Silk', 'Luxury', 'Gold'],
    description: 'A hand-loomed golden silk wedding sherwani with detailed zari collar and cuff borders.',
    renderConfig: { baseColor: '#D4AF37', secondaryColor: '#FFFFF0', texture: 'brocade' }
  },
  {
    id: 'm_full_tuxedo_dinner_suit',
    name: 'Midnight Tuxedo Dinner Suit',
    type: 'full',
    category: 'Formal',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#0A0A0A', '#FFFFFF'],
    price: 395,
    rating: 4.9,
    styleTags: ['Formal', 'Classic', 'Luxury', 'Black'],
    description: 'A classic double-breasted midnight black dinner tuxedo featuring satin-faced lapels.',
    renderConfig: { baseColor: '#0A0A0A', secondaryColor: '#FFFFFF', texture: 'plain' }
  },
  {
    id: 'm_top_sage_corduroy',
    name: 'Sage Corduroy Overshirt',
    type: 'top',
    category: 'Casual',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#8FBC8F', '#5C4033'],
    price: 95,
    rating: 4.7,
    styleTags: ['Casual', 'Vintage', 'Knit', 'Sage'],
    description: 'A vintage-wash sage green cotton corduroy overshirt with double utility flap pockets.',
    renderConfig: { baseColor: '#8FBC8F', secondaryColor: '#5C4033', texture: 'denim' }
  },
  {
    id: 'm_shoes_caramel_chelsea',
    name: 'Caramel Suede Chelsea Boots',
    type: 'shoes',
    category: 'Luxury',
    subcategory: 'Boots',
    gender: 'man',
    colors: ['#C68E17'],
    price: 190,
    rating: 4.8,
    styleTags: ['Suede', 'Boots', 'Classic', 'Caramel'],
    description: 'Hand-finished caramel brown suede Chelsea boots with flexible crepe rubber soles.',
    renderConfig: { baseColor: '#C68E17', texture: 'plain' }
  },
  {
    id: 'm_top_navy_breton',
    name: 'Navy Breton Stripe Tee',
    type: 'top',
    category: 'Vacation',
    subcategory: 'T-Shirts',
    gender: 'man',
    colors: ['#0F2C59', '#FFFFFF'],
    price: 50,
    rating: 4.6,
    styleTags: ['Vacation', 'Summer', 'Stripes', 'Blue'],
    description: 'A classic French navy blue and white horizontal stripe cotton Breton summer tee.',
    renderConfig: { baseColor: '#0F2C59', secondaryColor: '#FFFFFF', texture: 'stripes' }
  },
  {
    id: 'w_full_scarlet_banarasi_lehenga',
    name: 'Scarlet Silk Banarasi Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#B22222', '#D4AF37'],
    price: 520,
    rating: 5.0,
    styleTags: ['Traditional', 'Lehenga', 'Silk', 'Luxury', 'Red'],
    description: 'A grand scarlet red silk lehenga woven with gold brocade work and an embroidered blouse.',
    renderConfig: { baseColor: '#B22222', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_full_ivory_slip_dress',
    name: 'Ivory Satin Slip Dress',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFFFF0', '#C0C0C0'],
    price: 260,
    rating: 4.9,
    styleTags: ['Luxury', 'Silk', 'Classic', 'Ivory'],
    description: 'A liquid-like ivory white silk satin slip dress featuring delicate spaghetti shoulder straps.',
    renderConfig: { baseColor: '#FFFFF0', secondaryColor: '#C0C0C0', texture: 'silk' }
  },
  {
    id: 'w_full_plum_velvet_dress',
    name: 'Plum Velvet Wrap Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#4E1A3D', '#D4AF37'],
    price: 290,
    rating: 4.9,
    styleTags: ['Party', 'Cocktail', 'Velvet', 'Luxury', 'Purple'],
    description: 'An elegant plum purple velvet long-sleeve wrap dress shimmering with a dynamic sweep.',
    renderConfig: { baseColor: '#4E1A3D', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'w_full_denim_boiler',
    name: 'Denim Utility Boiler Suit',
    type: 'full',
    category: 'Casual',
    subcategory: 'Suits',
    gender: 'woman',
    colors: ['#4682B4', '#CD7F32'],
    price: 175,
    rating: 4.7,
    styleTags: ['Casual', 'Denim', 'Utility', 'Blue'],
    description: 'A structured mid-wash indigo denim boiler suit detailed with copper zipper lines.',
    renderConfig: { baseColor: '#4682B4', secondaryColor: '#CD7F32', texture: 'denim' }
  },
  {
    id: 'w_acc_rose_clutch',
    name: 'Rose Satin Clutch Bag',
    type: 'accessory',
    category: 'Luxury',
    subcategory: 'Bags',
    gender: 'woman',
    colors: ['#FFB6C1', '#D4AF37'],
    price: 110,
    rating: 4.8,
    styleTags: ['Luxury', 'Satin', 'Rose', 'Evening'],
    description: 'A delicate rose pink satin evening clutch with an ornate gold leaf snap clasp lock.',
    renderConfig: { baseColor: '#FFB6C1', secondaryColor: '#D4AF37', texture: 'plain' }
  },
  {
    id: 'm_top_cyber_tech_jacket',
    name: 'Cyberpunk Tech Jacket',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#0F0F1A', '#00F3FF'],
    price: 215,
    rating: 4.9,
    styleTags: ['Streetwear', 'Techwear', 'Cyberpunk', 'Black', 'Cyan'],
    description: 'A futuristic holographic black tech jacket with reflective neon cyan piping and chest utility buckle straps.',
    renderConfig: { baseColor: '#0F0F1A', secondaryColor: '#00F3FF', texture: 'artistic' }
  },
  {
    id: 'm_bot_mustard_corduroy',
    name: 'Mustard Corduroy Trousers',
    type: 'bottom',
    category: 'Casual',
    subcategory: 'Trousers',
    gender: 'man',
    colors: ['#D4A373'],
    price: 110,
    rating: 4.6,
    styleTags: ['Casual', 'Vintage', 'Retro', 'Mustard', 'Corduroy'],
    description: 'Classic golden mustard corduroy trousers in a relaxed, straight-leg vintage fit.',
    renderConfig: { baseColor: '#D4A373', texture: 'plain' }
  },
  {
    id: 'm_top_houndstooth_blazer',
    name: 'Houndstooth Plaid Blazer',
    type: 'top',
    category: 'Business',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#FFFFFF', '#1A1A1A'],
    price: 290,
    rating: 4.8,
    styleTags: ['Business', 'Formal', 'Vintage', 'Houndstooth', 'Plaid'],
    description: 'A double-breasted houndstooth patterned wool blazer with peak lapels and structured shoulders.',
    renderConfig: { baseColor: '#FFFFFF', secondaryColor: '#1A1A1A', texture: 'plaid' }
  },
  {
    id: 'm_full_sage_sherwani',
    name: 'Sage Silk Minimalist Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#778C74', '#F5F5DC'],
    price: 470,
    rating: 4.9,
    styleTags: ['Traditional', 'Sherwani', 'Silk', 'Luxury', 'Sage'],
    description: 'A minimalist sage green hand-woven raw silk sherwani detailed with delicate cream piping collars.',
    renderConfig: { baseColor: '#778C74', secondaryColor: '#F5F5DC', texture: 'silk' }
  },
  {
    id: 'm_top_vintage_denim_jacket',
    name: 'Acid-Wash Distressed Denim Jacket',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#A4C3D2', '#CD7F32'],
    price: 145,
    rating: 4.7,
    styleTags: ['Streetwear', 'Vintage', 'Denim', 'Blue'],
    description: 'An acid-wash light blue distressed denim trucker jacket with heavy copper buttons.',
    renderConfig: { baseColor: '#A4C3D2', secondaryColor: '#CD7F32', texture: 'denim' }
  },
  {
    id: 'w_full_cyber_fuchsia_trench',
    name: 'Cyber Fuchsia Vinyl Gown',
    type: 'full',
    category: 'Streetwear',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FF007F', '#FAFAFA'],
    price: 310,
    rating: 4.9,
    styleTags: ['Streetwear', 'Futuristic', 'Cyberpunk', 'Fuchsia', 'Vinyl'],
    description: 'A neon fuchsia pink vinyl-look trench gown detailed with reflective cyberpunk silver trim lines.',
    renderConfig: { baseColor: '#FF007F', secondaryColor: '#FAFAFA', texture: 'artistic' }
  },
  {
    id: 'w_full_emerald_zardozi_lehenga',
    name: 'Emerald Gold Zardozi Velvet Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#004B23', '#D4AF37'],
    price: 540,
    rating: 5.0,
    styleTags: ['Traditional', 'Lehenga', 'Velvet', 'Luxury', 'Gold'],
    description: 'A royal emerald green heavy velvet lehenga hand-embroidered with detailed gold zardozi wire borders.',
    renderConfig: { baseColor: '#004B23', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'w_full_cream_knit_dress',
    name: 'Cream Turtle-Neck Knit Dress',
    type: 'full',
    category: 'Casual',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFFDD0', '#A18262'],
    price: 210,
    rating: 4.8,
    styleTags: ['Casual', 'Cozy', 'Winter', 'Knitted', 'Cream'],
    description: 'A soft organic cream-white heavy cable-knit sweater dress featuring a folded turtleneck collar.',
    renderConfig: { baseColor: '#FFFDD0', secondaryColor: '#A18262', texture: 'knitted' }
  },
  {
    id: 'w_full_ruby_halter_gown',
    name: 'Ruby Satin Halter Neck Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#9B111E', '#D4AF37'],
    price: 390,
    rating: 4.9,
    styleTags: ['Luxury', 'Gown', 'Silk', 'Halter', 'Ruby'],
    description: 'An exquisite ruby red silk halter neck evening gown draped with a fluid, sweeping bias-cut skirt.',
    renderConfig: { baseColor: '#9B111E', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_top_leopard_satin_blouse',
    name: 'Bold Leopard Cowl Blouse',
    type: 'top',
    category: 'Party',
    subcategory: 'Blouses',
    gender: 'woman',
    colors: ['#D2A164', '#2B1A0A'],
    price: 130,
    rating: 4.7,
    styleTags: ['Party', 'Bold', 'Satin', 'Leopard', 'Animal Print'],
    description: 'A bold leopard print silk-satin blouse featuring a draped cowl neckline and puff sleeve cuffs.',
    renderConfig: { baseColor: '#D2A164', secondaryColor: '#2B1A0A', texture: 'artistic' }
  },
  {
    id: 'w_full_maroon_anarkali',
    name: 'Royal Maroon Silk Anarkali Gown',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#4A0E17', '#D4AF37'],
    price: 520,
    rating: 5.0,
    styleTags: ['Traditional', 'Anarkali', 'Luxury', 'Maroon', 'Gold', 'Brocade'],
    description: 'A floor-length royal maroon silk Anarkali suit with gold zari embroidery flares and scalloped hemline.',
    renderConfig: { baseColor: '#4A0E17', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_full_silver_runway_trench',
    name: 'Metallic Silver Runway Trench Dress',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#C0C0C0', '#FAFAFA'],
    price: 460,
    rating: 4.9,
    styleTags: ['Runway', 'Luxury', 'Silver', 'Metallic', 'Trench', 'V-Neck'],
    description: 'A high-fashion metallic silver liquid satin trench gown with dramatic folded lapels and silver filigree trim.',
    renderConfig: { baseColor: '#C0C0C0', secondaryColor: '#FAFAFA', texture: 'silk' }
  },
  {
    id: 'w_full_emerald_slip_dress',
    name: 'Emerald Green Satin Slip Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#046307', '#D4AF37'],
    price: 240,
    rating: 4.8,
    styleTags: ['Party', 'Satin', 'Emerald', 'Slip Dress', 'V-Neck'],
    description: 'An elegant jewel-tone emerald green satin midi slip dress with delicate gold spaghetti straps.',
    renderConfig: { baseColor: '#046307', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'w_full_pastel_floral_maxi',
    name: 'Blush Pink Floral Chiffon Maxi',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFD1DC', '#E63946'],
    price: 195,
    rating: 4.7,
    styleTags: ['Vacation', 'Floral', 'Chiffon', 'Pink', 'Boho'],
    description: 'A romantic blush pink floral printed chiffon maxi dress featuring layered tiered skirt pleats.',
    renderConfig: { baseColor: '#FFD1DC', secondaryColor: '#E63946', texture: 'artistic' }
  },
  {
    id: 'w_full_offshoulder_velvet_gown',
    name: 'Midnight Black Off-Shoulder Velvet Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0B0C10', '#D4AF37'],
    price: 490,
    rating: 5.0,
    styleTags: ['Luxury', 'Gown', 'Velvet', 'Off-Shoulder', 'Black', 'Gold'],
    description: 'A luxurious midnight black velvet ballgown styled with off-shoulder draped sleeves and rich rim-light sheen.',
    renderConfig: { baseColor: '#0B0C10', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'm_top_midnight_velvet_blazer',
    name: 'Midnight Navy Velvet Smoking Blazer',
    type: 'top',
    category: 'Business',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#000033', '#C0C0C0'],
    price: 340,
    rating: 4.9,
    styleTags: ['Business', 'Formal', 'Velvet', 'Blazer', 'Navy', 'Silver'],
    description: 'A plush midnight navy velvet tuxedo blazer with silver satin shawl lapels and silk lining.',
    renderConfig: { baseColor: '#000033', secondaryColor: '#C0C0C0', texture: 'velvet' }
  },
  {
    id: 'm_top_indigo_kimono_jacket',
    name: 'Japanese Indigo Shibori Kimono Jacket',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#1D3557', '#F1FAEE'],
    price: 180,
    rating: 4.8,
    styleTags: ['Streetwear', 'Kimono', 'Indigo', 'Artistic', 'Japanese'],
    description: 'An authentic Japanese deep indigo dyed Shibori patterned kimono jacket with open drape front.',
    renderConfig: { baseColor: '#1D3557', secondaryColor: '#F1FAEE', texture: 'artistic' }
  },
  {
    id: 'm_full_gold_embroidered_sherwani',
    name: 'Ivory Gold Zardozi Court Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#FFFFF0', '#D4AF37'],
    price: 580,
    rating: 5.0,
    styleTags: ['Traditional', 'Sherwani', 'Ivory', 'Gold', 'Luxury', 'Brocade'],
    description: 'A grand ivory royal court sherwani encrusted with gold zari damask motifs and scalloped collar trim.',
    renderConfig: { baseColor: '#FFFFF0', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'm_top_vintage_leather_bomber',
    name: 'Espresso Brown Distressed Leather Bomber',
    type: 'top',
    category: 'Casual',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#3B2314', '#D4A373'],
    price: 275,
    rating: 4.8,
    styleTags: ['Casual', 'Vintage', 'Leather', 'Bomber', 'Brown'],
    description: 'A vintage espresso brown pebbled leather bomber jacket detailed with ribbed knit collar cuffs.',
    renderConfig: { baseColor: '#3B2314', secondaryColor: '#D4A373', texture: 'leather' }
  },
  {
    id: 'w_top_diamond_sequin_crop',
    name: 'Diamond Champagne Sequin Party Top',
    type: 'top',
    category: 'Party',
    subcategory: 'Blouses',
    gender: 'woman',
    colors: ['#F7E7CE', '#FFFFFF'],
    price: 160,
    rating: 4.9,
    styleTags: ['Party', 'Sequins', 'Sparkle', 'Champagne', 'Glitz'],
    description: 'A glittering champagne gold sequined party top with dual-pass lens flare halos and V-neck line.',
    renderConfig: { baseColor: '#F7E7CE', secondaryColor: '#FFFFFF', texture: 'sequins' }
  },
  {
    id: 'w_full_banarasi_bridal_lehenga_8k',
    name: '8K Golden Zari Banarasi Silk Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#800020', '#FFD700'],
    price: 650,
    rating: 5.0,
    styleTags: ['Traditional', 'Lehenga', 'Banarasi', 'Gold', 'Bridal', 'Luxury', 'Brocade'],
    description: 'An 8K hyper-realistic crimson maroon Banarasi silk bridal lehenga woven with intricate 24K gold zari damask medallions.',
    renderConfig: { baseColor: '#800020', secondaryColor: '#FFD700', texture: 'brocade' }
  },
  {
    id: 'm_top_diamond_velvet_blazer_8k',
    name: '8K Midnight Diamond Sequin Velvet Blazer',
    type: 'top',
    category: 'Luxury',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#0A0A1A', '#E5E4E2'],
    price: 480,
    rating: 5.0,
    styleTags: ['Luxury', 'Blazer', 'Velvet', 'Sequins', 'Runway', 'Platinum'],
    description: 'A 8K luxury midnight blue velvet dinner jacket encrusted with micro-platinum sequin pinstripes and satin lapels.',
    renderConfig: { baseColor: '#0A0A1A', secondaryColor: '#E5E4E2', texture: 'velvet' }
  },
  {
    id: 'w_full_emerald_bias_gown_8k',
    name: '8K Emerald Satin Bias-Cut Evening Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#014421', '#D4AF37'],
    price: 510,
    rating: 4.9,
    styleTags: ['Luxury', 'Gown', 'Satin', 'Emerald', 'V-Neck', 'Runway'],
    description: 'An 8K fluid emerald green liquid satin bias-cut gown featuring iridescent pearl sheen and sweeping train hem.',
    renderConfig: { baseColor: '#014421', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'm_top_cyber_hologram_trench_8k',
    name: '8K Cyberpunk Hologram Neon Trench Coat',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#120024', '#00FFCC'],
    price: 390,
    rating: 4.9,
    styleTags: ['Streetwear', 'Cyberpunk', 'Hologram', 'Neon', 'Techwear', 'Artistic'],
    description: 'An 8K futuristic holographic dark purple tech trench coat accented with glowing neon turquoise vector trim lines.',
    renderConfig: { baseColor: '#120024', secondaryColor: '#00FFCC', texture: 'artistic' }
  },
  {
    id: 'w_full_ruby_pallu_saree_8k',
    name: '8K Royal Ruby Silk Saree with Gold Pallu',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#B00020', '#FFDF00'],
    price: 540,
    rating: 5.0,
    styleTags: ['Traditional', 'Saree', 'Ruby', 'Gold', 'Silk', 'Filigree'],
    description: 'An 8K royal ruby red pure Kanjeevaram silk saree with a heavily woven gold filigree pallu and scalloped zari border.',
    renderConfig: { baseColor: '#B00020', secondaryColor: '#FFDF00', texture: 'silk' }
  },
  {
    id: 'm_full_ivory_chikan_sherwani_8k',
    name: '8K Ivory Kashmiri Hand-Embroidered Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#FFFFF5', '#C0C0C0'],
    price: 610,
    rating: 5.0,
    styleTags: ['Traditional', 'Sherwani', 'Ivory', 'Kashmiri', 'Silver', 'Brocade'],
    description: 'An 8K masterwork ivory raw silk sherwani featuring intricate silver wire thread work and regal mandarin collar.',
    renderConfig: { baseColor: '#FFFFF5', secondaryColor: '#C0C0C0', texture: 'brocade' }
  },
  {
    id: 'm_top_obsidian_biker_jacket_8k',
    name: '8K Obsidian Italian Leather Biker Jacket',
    type: 'top',
    category: 'Casual',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#080808', '#E0E0E0'],
    price: 430,
    rating: 4.9,
    styleTags: ['Casual', 'Leather', 'Biker', 'Obsidian', 'Vintage'],
    description: 'An 8K full-grain Italian black calfskin leather biker jacket with asymmetric silver chrome hardware zippers.',
    renderConfig: { baseColor: '#080808', secondaryColor: '#E0E0E0', texture: 'leather' }
  },
  {
    id: 'w_full_champagne_rose_slip_8k',
    name: '8K Champagne Rose Pearl Silk Slip Dress',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#F4C2C2', '#FFFFFF'],
    price: 320,
    rating: 4.9,
    styleTags: ['Party', 'Slip Dress', 'Silk', 'Rose', 'Champagne', 'Pearl'],
    description: 'An 8K champagne rose pink mulberry silk slip dress with soft pearl luster sheen and cowl neck line.',
    renderConfig: { baseColor: '#F4C2C2', secondaryColor: '#FFFFFF', texture: 'silk' }
  },
  {
    id: 'm_top_nordic_cashmere_turtleneck_8k',
    name: '8K Nordic Cable-Knit Cashmere Turtleneck',
    type: 'top',
    category: 'Casual',
    subcategory: 'Sweaters',
    gender: 'man',
    colors: ['#2F4F4F', '#8FBC8F'],
    price: 260,
    rating: 4.8,
    styleTags: ['Casual', 'Knitted', 'Cashmere', 'Nordic', 'Winter'],
    description: 'An 8K heavy slate green cable-knit Mongolian cashmere turtleneck sweater with interlocking V-stitch columns.',
    renderConfig: { baseColor: '#2F4F4F', secondaryColor: '#8FBC8F', texture: 'knitted' }
  },
  {
    id: 'w_full_sapphire_offshoulder_gown_8k',
    name: '8K Sapphire Blue Velvet Off-Shoulder Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0F2027', '#FFD700'],
    price: 590,
    rating: 5.0,
    styleTags: ['Luxury', 'Gown', 'Velvet', 'Sapphire', 'Off-Shoulder', 'Gold'],
    description: 'An 8K royal sapphire blue velvet off-shoulder gown with golden filigree embroidery borders and rim-light sheen.',
    renderConfig: { baseColor: '#0F2027', secondaryColor: '#FFD700', texture: 'velvet' }
  },
  {
    id: 'w_full_peacock_kanjeevaram_saree',
    name: 'Royal Gold & Peacock Blue Silk Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#005F73', '#FFD700'],
    price: 570,
    rating: 5.0,
    styleTags: ['Traditional', 'Saree', 'Peacock Blue', 'Gold', 'Kanjeevaram', 'Silk'],
    description: 'A striking royal peacock blue Kanjeevaram silk saree with a heavily woven 24K gold zari pallu and scalloped lace borders.',
    renderConfig: { baseColor: '#005F73', secondaryColor: '#FFD700', texture: 'silk' }
  },
  {
    id: 'm_full_mughal_crimson_sherwani',
    name: 'Imperial Crimson Velvet Mughal Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#990000', '#FFD700'],
    price: 640,
    rating: 5.0,
    styleTags: ['Traditional', 'Sherwani', 'Mughal', 'Crimson', 'Velvet', 'Gold'],
    description: 'An imperial red plush velvet court sherwani hand-embroidered with intricate gold zardozi damask medallions.',
    renderConfig: { baseColor: '#990000', secondaryColor: '#FFD700', texture: 'velvet' }
  },
  {
    id: 'w_full_starlight_violet_gown',
    name: 'Starlight Diamond Sequin Violet Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#2A0845', '#E0BBE4'],
    price: 530,
    rating: 4.9,
    styleTags: ['Luxury', 'Gown', 'Sequins', 'Violet', 'Halter', 'Sparkle'],
    description: 'A glittering deep violet halter evening gown encrusted with starlight micro-diamond sequin halos and sweeping bias skirt.',
    renderConfig: { baseColor: '#2A0845', secondaryColor: '#E0BBE4', texture: 'sequins' }
  },
  {
    id: 'w_top_cherry_blossom_kimono',
    name: 'Japanese Cherry Blossom Pink Silk Kimono',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Jackets',
    gender: 'woman',
    colors: ['#FFB7C5', '#FFD700'],
    price: 240,
    rating: 4.9,
    styleTags: ['Streetwear', 'Kimono', 'Silk', 'Pink', 'Floral', 'Artistic'],
    description: 'An authentic Japanese cherry blossom pink mulberry silk open kimono robe with metallic gold obi sash trim.',
    renderConfig: { baseColor: '#FFB7C5', secondaryColor: '#FFD700', texture: 'artistic' }
  },
  {
    id: 'm_top_ivory_black_lapel_tuxedo',
    name: 'Ivory Double-Breasted Black Satin Tuxedo',
    type: 'top',
    category: 'Business',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#FFFFF0', '#0A0A0A'],
    price: 450,
    rating: 5.0,
    styleTags: ['Business', 'Formal', 'Tuxedo', 'Ivory', 'Black', 'Blazer'],
    description: 'A classic formal ivory double-breasted tuxedo jacket featuring contrasting jet black silk satin peak lapels.',
    renderConfig: { baseColor: '#FFFFF0', secondaryColor: '#0A0A0A', texture: 'plain' }
  },
  {
    id: 'w_full_emerald_filigree_anarkali',
    name: 'Emerald Filigree Scalloped Chiffon Anarkali',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0B6623', '#D4AF37'],
    price: 510,
    rating: 4.9,
    styleTags: ['Traditional', 'Anarkali', 'Emerald', 'Gold', 'Chiffon', 'Lace'],
    description: 'A floor-length deep emerald green pleated chiffon Anarkali with gold filigree waist belt embroidery and scalloped hem.',
    renderConfig: { baseColor: '#0B6623', secondaryColor: '#D4AF37', texture: 'brocade' }
  },
  {
    id: 'w_top_vintage_tan_suede_fringe',
    name: 'Vintage Tan Suede Western Fringe Jacket',
    type: 'top',
    category: 'Casual',
    subcategory: 'Jackets',
    gender: 'woman',
    colors: ['#C19A6B', '#5C4033'],
    price: 290,
    rating: 4.8,
    styleTags: ['Casual', 'Vintage', 'Suede', 'Boho', 'Tan'],
    description: 'A western-style tan brown soft suede leather jacket detailed with cascading chest fringes and whipstitch trim.',
    renderConfig: { baseColor: '#C19A6B', secondaryColor: '#5C4033', texture: 'leather' }
  },
  {
    id: 'm_top_matrix_neon_trench',
    name: 'Cyberpunk Neon Wireframe Rain Trench',
    type: 'top',
    category: 'Streetwear',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#101014', '#39FF14'],
    price: 380,
    rating: 4.9,
    styleTags: ['Streetwear', 'Cyberpunk', 'Matrix', 'Neon', 'Techwear'],
    description: 'A translucent dark charcoal matrix tech trench coat piped with glowing neon lime vector grid lines.',
    renderConfig: { baseColor: '#101014', secondaryColor: '#39FF14', texture: 'artistic' }
  },
  {
    id: 'w_full_burgundy_corset_ballgown',
    name: 'Burgundy Velvet Boned Corset Ballgown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#58111A', '#FFD700'],
    price: 620,
    rating: 5.0,
    styleTags: ['Luxury', 'Gown', 'Velvet', 'Burgundy', 'Corset', 'Ballgown'],
    description: 'A majestic deep burgundy plush velvet ballgown featuring a structured boned corset bodice and off-shoulder drape.',
    renderConfig: { baseColor: '#58111A', secondaryColor: '#FFD700', texture: 'velvet' }
  },
  {
    id: 'm_full_beige_linen_summer_suit',
    name: 'Beige Italian Linen Double-Breasted Suit',
    type: 'full',
    category: 'Casual',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#D7C4B7', '#FFFFFF'],
    price: 360,
    rating: 4.8,
    styleTags: ['Casual', 'Linen', 'Beige', 'Italian', 'Summer', 'Suit'],
    description: 'A crisp sand beige pure Italian linen double-breasted suit designed for effortless warm weather elegance.',
    renderConfig: { baseColor: '#D7C4B7', secondaryColor: '#FFFFFF', texture: 'plain' }
  },
  // --- TENTH BATCH: 20 ULTRA-UNIQUE MASTERPIECE GARMENTS (10 MEN'S, 10 WOMEN'S) ---
  {
    id: 'm_full_midnight_tuxedo_gold_lapels',
    name: 'Midnight Navy Velvet Tuxedo with Gold Lapels',
    type: 'full',
    category: 'Party',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#0A1128', '#D4AF37'],
    price: 520,
    rating: 5.0,
    styleTags: ['Party', 'Tuxedo', 'Velvet', 'Navy', 'Gold', 'Luxury'],
    description: 'A plush midnight navy velvet tuxedo with 24K gold zari piping lapels and silk trousers.',
    renderConfig: { baseColor: '#0A1128', secondaryColor: '#D4AF37', texture: 'velvet' }
  },
  {
    id: 'm_full_emerald_raw_silk_sherwani',
    name: 'Emerald Green Raw Silk Court Sherwani',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sherwani',
    gender: 'man',
    colors: ['#004B23', '#FFD700'],
    price: 590,
    rating: 5.0,
    styleTags: ['Traditional', 'Sherwani', 'Emerald', 'Gold', 'Silk'],
    description: 'A royal court emerald green raw silk sherwani intricately hand-embroidered with gold thread motifs.',
    renderConfig: { baseColor: '#004B23', secondaryColor: '#FFD700', texture: 'brocade' }
  },
  {
    id: 'm_full_charcoal_pinstripe_business_suit',
    name: 'Charcoal Italian Pinstripe Business Suit',
    type: 'full',
    category: 'Business',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#1C1C1C', '#E0E0E0'],
    price: 490,
    rating: 4.9,
    styleTags: ['Business', 'Formal', 'Pinstripe', 'Suit', 'Charcoal'],
    description: 'A sharp 3-piece charcoal wool suit detailed with crisp white micro-pinstripes and silk lining.',
    renderConfig: { baseColor: '#1C1C1C', secondaryColor: '#E0E0E0', texture: 'stripes' }
  },
  {
    id: 'm_top_terracotta_linen_shirt',
    name: 'Terracotta Orange Cuban Linen Shirt',
    type: 'top',
    category: 'Vacation',
    subcategory: 'Shirts',
    gender: 'man',
    colors: ['#C85A32', '#F4F1DE'],
    price: 85,
    rating: 4.7,
    styleTags: ['Vacation', 'Linen', 'Terracotta', 'Cuban Collar', 'Summer'],
    description: 'A breezy terracotta orange pure linen shirt with a retro camp collar and shell buttons.',
    renderConfig: { baseColor: '#C85A32', secondaryColor: '#F4F1DE', texture: 'plain' }
  },
  {
    id: 'm_bot_white_linen_trousers',
    name: 'Relaxed White Linen Vacation Trousers',
    type: 'bottom',
    category: 'Vacation',
    subcategory: 'Trousers',
    gender: 'man',
    colors: ['#F9F9F9', '#CCCCCC'],
    price: 95,
    rating: 4.8,
    styleTags: ['Vacation', 'Linen', 'White', 'Relaxed', 'Summer'],
    description: 'Lightweight white linen drawstring trousers with side seam pockets.',
    renderConfig: { baseColor: '#F9F9F9', texture: 'plain' }
  },
  {
    id: 'm_full_bordeaux_brocade_jacket_suit',
    name: 'Bordeaux Red Brocade Dinner Jacket Suit',
    type: 'full',
    category: 'Party',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#58111A', '#FFD700'],
    price: 540,
    rating: 4.9,
    styleTags: ['Party', 'Brocade', 'Red', 'Gold', 'Blazer'],
    description: 'A opulent bordeaux red floral silk brocade dinner jacket with black satin shawl collar.',
    renderConfig: { baseColor: '#58111A', secondaryColor: '#FFD700', texture: 'brocade' }
  },
  {
    id: 'm_top_olive_safari_overshirt',
    name: 'Olive Green Utility Safari Overshirt',
    type: 'top',
    category: 'Casual',
    subcategory: 'Jackets',
    gender: 'man',
    colors: ['#3A5A40', '#A3B18A'],
    price: 110,
    rating: 4.8,
    styleTags: ['Casual', 'Safari', 'Utility', 'Olive', 'Cotton'],
    description: 'Heavyweight cotton canvas safari jacket with four flap pockets and waist cinch.',
    renderConfig: { baseColor: '#3A5A40', texture: 'plain' }
  },
  {
    id: 'm_full_sapphire_kurta_bandhgala_set',
    name: 'Sapphire Blue Silk Kurta Bandhgala Set',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Kurta',
    gender: 'man',
    colors: ['#0A2540', '#D4AF37'],
    price: 430,
    rating: 4.9,
    styleTags: ['Traditional', 'Kurta', 'Bandhgala', 'Sapphire', 'Gold'],
    description: 'A deep sapphire blue silk kurta paired with a gold buttoned mandarin collar waist jacket.',
    renderConfig: { baseColor: '#0A2540', secondaryColor: '#D4AF37', texture: 'silk' }
  },
  {
    id: 'm_top_mustard_knit_polo',
    name: 'Mustard Yellow Ribbed Knit Polo',
    type: 'top',
    category: 'Casual',
    subcategory: 'Polos',
    gender: 'man',
    colors: ['#E9C46A', '#264653'],
    price: 75,
    rating: 4.7,
    styleTags: ['Casual', 'Knit', 'Mustard', 'Polo', 'Retro'],
    description: 'A 70s-inspired mustard yellow fine-gauge cotton knit polo with open collar.',
    renderConfig: { baseColor: '#E9C46A', texture: 'knitted' }
  },
  {
    id: 'm_full_cyber_neon_matrix_suit',
    name: 'Cyberpunk Neon Wireframe Tech Suit',
    type: 'full',
    category: 'Streetwear',
    subcategory: 'Suits',
    gender: 'man',
    colors: ['#0D0D11', '#00E5FF'],
    price: 460,
    rating: 5.0,
    styleTags: ['Streetwear', 'Cyberpunk', 'Techwear', 'Neon', 'Cyan'],
    description: 'A dark matte tech suit illuminated with glowing neon cyan vector grid lines.',
    renderConfig: { baseColor: '#0D0D11', secondaryColor: '#00E5FF', texture: 'artistic' }
  },
  {
    id: 'w_full_ruby_zardozi_velvet_lehenga',
    name: 'Ruby Red Velvet Zardozi Bridal Lehenga',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Lehengas',
    gender: 'woman',
    colors: ['#800000', '#FFD700'],
    price: 680,
    rating: 5.0,
    styleTags: ['Traditional', 'Lehenga', 'Ruby', 'Velvet', 'Gold', 'Bridal'],
    description: 'A grand bridal ruby red velvet lehenga choli heavily embroidered with gold zardozi filigree work.',
    renderConfig: { baseColor: '#800000', secondaryColor: '#FFD700', texture: 'velvet' }
  },
  {
    id: 'w_full_champagne_crystal_mermaid_gown',
    name: 'Champagne Gold Crystal Mermaid Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#F7E7CE', '#FFFFFF'],
    price: 640,
    rating: 5.0,
    styleTags: ['Luxury', 'Gown', 'Champagne', 'Sequins', 'Mermaid', 'Sparkle'],
    description: 'A red-carpet champagne gold liquid satin mermaid gown encrusted with thousands of micro-crystals.',
    renderConfig: { baseColor: '#F7E7CE', secondaryColor: '#FFFFFF', texture: 'sequins' }
  },
  {
    id: 'w_full_emerald_kanjeevaram_brocade_saree',
    name: 'Emerald Green Kanjeevaram Zari Saree',
    type: 'full',
    category: 'Traditional',
    subcategory: 'Sarees',
    gender: 'woman',
    colors: ['#014421', '#FFD700'],
    price: 580,
    rating: 4.9,
    styleTags: ['Traditional', 'Saree', 'Emerald', 'Gold', 'Kanjeevaram'],
    description: 'A rich emerald green pure Kanjeevaram silk saree with a 24K gold zari peacock motif pallu.',
    renderConfig: { baseColor: '#014421', secondaryColor: '#FFD700', texture: 'silk' }
  },
  {
    id: 'w_full_midnight_sapphire_corset_dress',
    name: 'Midnight Sapphire Silk Corset Midi',
    type: 'full',
    category: 'Party',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#0F2027', '#E0BBE4'],
    price: 340,
    rating: 4.9,
    styleTags: ['Party', 'Corset', 'Sapphire', 'Silk', 'Midi'],
    description: 'A boned sapphire blue silk satin midi dress featuring a draped sweetheart neckline.',
    renderConfig: { baseColor: '#0F2027', secondaryColor: '#E0BBE4', texture: 'silk' }
  },
  {
    id: 'w_full_blush_pink_tiered_organza_gown',
    name: 'Blush Pink Tiered Organza Princess Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FFC0CB', '#FFFFFF'],
    price: 490,
    rating: 4.8,
    styleTags: ['Luxury', 'Gown', 'Organza', 'Pink', 'Princess'],
    description: 'A romantic blush pink layered organza ballgown featuring off-shoulder ruffle sleeves.',
    renderConfig: { baseColor: '#FFC0CB', secondaryColor: '#FFFFFF', texture: 'plain' }
  },
  {
    id: 'w_top_lavender_cashmere_sweater',
    name: 'Soft Lavender Mongolian Cashmere Knit',
    type: 'top',
    category: 'Casual',
    subcategory: 'Sweaters',
    gender: 'woman',
    colors: ['#E6E6FA', '#FFFFFF'],
    price: 190,
    rating: 4.8,
    styleTags: ['Casual', 'Cashmere', 'Lavender', 'Knit', 'Winter'],
    description: 'Ultra-soft pure lavender Mongolian cashmere sweater with a relaxed crew neck.',
    renderConfig: { baseColor: '#E6E6FA', texture: 'knitted' }
  },
  {
    id: 'w_bot_cream_wide_leg_trousers',
    name: 'Cream Pleated Wide-Leg Tailored Pants',
    type: 'bottom',
    category: 'Casual',
    subcategory: 'Trousers',
    gender: 'woman',
    colors: ['#FFFDD0', '#D4AF37'],
    price: 130,
    rating: 4.7,
    styleTags: ['Casual', 'Tailored', 'Cream', 'Wide Leg'],
    description: 'High-waisted cream crepe wide-leg trousers with front pleats.',
    renderConfig: { baseColor: '#FFFDD0', texture: 'plain' }
  },
  {
    id: 'w_full_cyber_hologram_violet_vinyl_gown',
    name: 'Cyberpunk Violet Holographic Vinyl Gown',
    type: 'full',
    category: 'Streetwear',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#4B0082', '#00FFCC'],
    price: 420,
    rating: 4.9,
    styleTags: ['Streetwear', 'Cyberpunk', 'Hologram', 'Vinyl', 'Violet'],
    description: 'A futuristic deep violet holographic vinyl gown reflecting iridescent cyan light streaks.',
    renderConfig: { baseColor: '#4B0082', secondaryColor: '#00FFCC', texture: 'artistic' }
  },
  {
    id: 'w_full_coral_chiffon_boho_maxi',
    name: 'Sunset Coral Pleated Chiffon Boho Maxi',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#FF7F50', '#FFD700'],
    price: 210,
    rating: 4.8,
    styleTags: ['Vacation', 'Chiffon', 'Coral', 'Maxi', 'Boho'],
    description: 'A vibrant coral pink pleated chiffon resort maxi dress with gold beaded neck tassels.',
    renderConfig: { baseColor: '#FF7F50', secondaryColor: '#FFD700', texture: 'plain' }
  },
  {
    id: 'w_full_black_velvet_gothic_gown',
    name: 'Obsidian Black Velvet Corset Gothic Gown',
    type: 'full',
    category: 'Luxury',
    subcategory: 'Dresses',
    gender: 'woman',
    colors: ['#050505', '#C0C0C0'],
    price: 560,
    rating: 5.0,
    styleTags: ['Luxury', 'Gown', 'Velvet', 'Black', 'Gothic'],
    description: 'A dramatic obsidian black velvet gown featuring a silver boned lace corset bodice.',
    renderConfig: { baseColor: '#050505', secondaryColor: '#C0C0C0', texture: 'velvet' }
  }
];

// Helper to generate kids items (boys/girls) based on base templates
export const KIDS_GARMENTS: Garment[] = [
  // --- BOY TOPS ---
  {
    id: 'b_top_graphic_yellow',
    name: 'Dino Graphic Cotton Tee',
    type: 'top',
    category: 'Casual',
    subcategory: 'Graphic',
    gender: 'boy',
    colors: ['#FFD369', '#3F72AF'],
    price: 22,
    rating: 4.6,
    styleTags: ['Comfort', 'Graphic', 'Cotton', 'Playground'],
    description: 'Soft organic cotton tee featuring a cool dinosaur skateboard graphic.',
    renderConfig: { baseColor: '#FFD700', texture: 'plain', logoText: 'RAWWR!' }
  },
  {
    id: 'b_top_hoodie_blue',
    name: 'Zip-Up Fleece Hoodie',
    type: 'top',
    category: 'Casual',
    subcategory: 'Hoodies',
    gender: 'boy',
    colors: ['#1A374D', '#406882'],
    price: 35,
    rating: 4.8,
    styleTags: ['Hooded', 'Fleece', 'Warm', 'Casual'],
    description: 'Cozy zip-up hoodie lined with ultra-soft fleece for outdoor play.',
    renderConfig: { baseColor: '#1A374D', texture: 'plain' }
  },
  // --- BOY BOTTOMS ---
  {
    id: 'b_bot_jogger_grey',
    name: 'Active Fleece Joggers',
    type: 'bottom',
    category: 'Casual',
    subcategory: 'Joggers',
    gender: 'boy',
    colors: ['#E5E5E5', '#222831'],
    price: 25,
    rating: 4.5,
    styleTags: ['Active', 'Drawstring', 'Comfort', 'Soft'],
    description: 'Lightweight joggers with reinforced knees and an adjustable elastic waistband.',
    renderConfig: { baseColor: '#808080', texture: 'plain' }
  },
  {
    id: 'b_bot_jeans_blue',
    name: 'Stretch Fit Denim',
    type: 'bottom',
    category: 'Casual',
    subcategory: 'Jeans',
    gender: 'boy',
    colors: ['#3282B8'],
    price: 28,
    rating: 4.7,
    styleTags: ['Stretch', 'Durable', 'Classic', 'Adjustable'],
    description: 'Super stretch denim designed to move with active play, featuring inner adjustable tabs.',
    renderConfig: { baseColor: '#4682B4', texture: 'denim' }
  },

  // --- GIRL TOPS ---
  {
    id: 'g_top_ruffle_pink',
    name: 'Ruffled Ribbed Top',
    type: 'top',
    category: 'Casual',
    subcategory: 'Crop Tops',
    gender: 'girl',
    colors: ['#FFC4DD', '#FFFFFF'],
    price: 24,
    rating: 4.7,
    styleTags: ['Ruffles', 'Ribbed', 'Cute', 'Cotton'],
    description: 'Adorable ribbed top featuring dainty ruffle detailing on the shoulders.',
    renderConfig: { baseColor: '#FFB6C1', texture: 'plain' }
  },
  // --- GIRL BOTTOMS ---
  {
    id: 'g_bot_skirt_denim',
    name: 'Button-Up Denim Skirt',
    type: 'bottom',
    category: 'Casual',
    subcategory: 'Mini Skirts',
    gender: 'girl',
    colors: ['#4F8A8B'],
    price: 26,
    rating: 4.6,
    styleTags: ['A-Line', 'Denim', 'Vintage', 'Button-up'],
    description: 'Sturdy A-line denim skirt featuring metallic buttons on the front.',
    renderConfig: { baseColor: '#5F9EA0', texture: 'denim' }
  },
  // --- GIRL FULL BODY ---
  {
    id: 'g_full_dress_floral',
    name: 'Tiered Floral Summer Dress',
    type: 'full',
    category: 'Vacation',
    subcategory: 'Maxi Dresses',
    gender: 'girl',
    colors: ['#FFABAB', '#FFD3B6', '#D8F3DC'],
    price: 39,
    rating: 4.9,
    styleTags: ['Floral', 'Tiered', 'Cotton', 'Summer'],
    description: 'A beautiful, flowing cotton dress with detailed wildflower patterns.',
    renderConfig: { baseColor: '#FFA07A', secondaryColor: '#2E8B57', texture: 'stripes' }
  }
];

// Complete combined garments list
export const ALL_GARMENTS = [...BASE_GARMENTS, ...KIDS_GARMENTS];

// A static dictionary of categories and themes
export const OUTFIT_CATEGORIES = [
  'Casual',
  'Streetwear',
  'Luxury',
  'Business',
  'College',
  'Office',
  'Party',
  'Traditional',
  'Travel',
  'Vacation',
  'Summer',
  'Winter',
  'Korean Fashion',
  'Japanese Fashion',
  'Vintage',
  'Y2K',
  'Techwear',
  'Old Money'
];

/**
 * Programmatic Outfit Catalog Builder
 * Generates 1,000+ unique outfit combinations.
 * Combines tops, bottoms, outerwear, shoes, and accessories
 * across different genders and styles, naming each outfit uniquely.
 */
export function generateOutfitLibrary(): Outfit[] {
  const library: Outfit[] = [];
  const genders: ('man' | 'woman' | 'boy' | 'girl')[] = ['man', 'woman', 'boy', 'girl'];
  
  let outfitCounter = 0;

  for (const gender of genders) {
    const genderGarments = ALL_GARMENTS.filter(g => {
      if (gender === 'man') return g.gender === 'man' || (g.gender === 'unisex' && g.type !== 'shoes' && g.type !== 'accessory');
      if (gender === 'woman') return g.gender === 'woman' || (g.gender === 'unisex' && g.type !== 'shoes' && g.type !== 'accessory');
      if (gender === 'boy') return g.gender === 'boy' || (g.gender === 'unisex' && g.type !== 'shoes' && g.type !== 'accessory');
      if (gender === 'girl') return g.gender === 'girl' || (g.gender === 'unisex' && g.type !== 'shoes' && g.type !== 'accessory');
      return false;
    });

    const tops = genderGarments.filter(g => g.type === 'top' || g.type === 'outerwear');
    const bottoms = genderGarments.filter(g => g.type === 'bottom');
    const fulls = genderGarments.filter(g => g.type === 'full');

    // 1. First add paired Top + Bottom complete outfits (Tees + Cargos, Shirts + Jeans, Blazers + Chinos) for instant masculine/feminine clarity!
    for (let i = 0; i < tops.length; i++) {
      outfitCounter++;
      const top = tops[i];
      const bottom = bottoms.length > 0 ? bottoms[i % bottoms.length] : null;
      const items = bottom ? [top, bottom] : [top];
      const totalPrice = items.reduce((sum, item) => sum + item.price, 0);

      library.push({
        id: `outfit_${gender}_${outfitCounter}_${top.id}`,
        name: bottom ? `${top.name} with ${bottom.name}` : top.name,
        gender: gender,
        category: top.category,
        styleTags: [...new Set([...top.styleTags, ...(bottom ? bottom.styleTags : [])])],
        items: items,
        description: bottom ? `${top.description} Paired with ${bottom.description.toLowerCase()}` : top.description,
        totalPrice: totalPrice
      });
    }

    // 2. Next add standalone Full-Body Suits & Traditional Sherwanis/Sarees/Gowns!
    for (const f of fulls) {
      outfitCounter++;
      library.push({
        id: `outfit_${gender}_${outfitCounter}_${f.id}`,
        name: f.name,
        gender: gender,
        category: f.category,
        styleTags: f.styleTags,
        items: [f],
        description: f.description,
        totalPrice: f.price
      });
    }
  }

  return library;
}